export const BATTLE_BACKGROUND_ASSET_KEYS = Object.freeze({
  FOREST: 'FOREST',
});

export const BATTLE_ASSET_KEYS = Object.freeze({
  HEALTH_BAR_BACKGROUND: 'HEALTH_BAR_BACKGROUND',
});

export const HEALTH_BAR_ASSET_KEYS = Object.freeze({
  LEFT_CAP: 'LEFT_CAP',
  MIDDLE: 'MIDDLE',
  RIGHT_CAP: 'RIGHT_CAP',
  LEFT_CAP_SHADOW: 'LEFT_CAP_SHADOW',
  MIDDLE_SHADOW: 'MIDDLE_SHADOW',
  RIGHT_CAP_SHADOW: 'RIGHT_CAP_SHADOW',
});

export const MONSTER_ASSET_KEYS = Object.freeze({
  IGUANIGNITE: 'IGUANIGNITE',
  CARNODUSK: 'CARNODUSK',
});

export const enum UI_ASSET_KEYS {
  CURSOR = 'CURSOR',
  CURSOR_WHITE = 'CURSOR_WHITE',
  MENU_BACKGROUND = 'MENU_BACKGROUND',
  MENU_BACKGROUND_GREEN = 'MENU_BACKGROUND_GREEN',
  MENU_BACKGROUND_PURPLE = 'MENU_BACKGROUND_PURPLE',
  BLUE_BUTTON = 'BLUE_BUTTON',
  BLUE_BUTTON_SELECTED = 'BLUE_BUTTON_SELECTED',
}

export const DATA_ASSET_KEYS = Object.freeze({
  ATTACKS: 'ATTACKS',
  ANIMATIONS: 'ANIMATIONS',
});

export const ATTACK_ASSET_KEYS = Object.freeze({
  ICE_SHARD: 'ICE_SHARD',
  ICE_SHARD_START: 'ICE_SHARD_START',
  SLASH: 'SLASH',
});

export const enum WORLD_ASSET_KEYS {
  WORLD_BACKGROUND = 'WORLD_BACKGROUND',
  WORLD_MAIN_LEVEL = 'WORLD_MAIN_LEVEL',
  WORLD_COLLISION = 'WORLD_COLLISION',
  WORLD_FOREGROUND = 'WORLD_FOREGROUND',
  WORLD_ENCOUNTER_ZONE = 'WORLD_ENCOUNTER_ZONE',
}

export const enum CHARACTER_ASSET_KEYS {
  PLAYER = 'PLAYER',
  NPC = 'NPC',
}

export const enum TITLE_ASSET_KEYS {
  BACKGROUND = 'BACKGROUND',
  TITLE = 'TITLE',
  PANEL = 'PANEL',
}

export const enum MONSTER_PARTY_ASSET_KEYS {
  PARTY_BACKGROUND = 'PARTY_BACKGROUND',
  MONSTER_DETAILS_BACKGROUND = 'MONSTER_DETAILS_BACKGROUND',
}

export const enum INVENTORY_ASSET_KEYS {
  INVENTORY_BACKGROUND = 'INVENTORY_BACKGROUND',
  INVENTORY_BAG = 'INVENTORY_BAG',
}
