export const enum OPTION_MENU_OPTIONS {
  TEXT_SPEED = 'TEXT_SPEED',
  BATTLE_SCENE = 'BATTLE_SCENE',
  BATTLE_STYLE = 'BATTLE_STYLE',
  SOUND = 'SOUND',
  VOLUME = 'VOLUME',
  MENU_COLOR = 'MENU_COLOR',
  CONFIRM = 'CONFIRM',
}
